[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''! has('nvim')'''
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''! has('nvim')'''
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
